-- local sources = { "nvim_lsp", "render-markdown", "luasnip", "orgmode", "path" }

-- local sources_gen = function()
-- 	local res = {}
-- 	for i, source in ipairs(sources) do
-- 		res[i] = { name = source }
-- 	end
--
-- 	res[#res + 1] = { name = "lazydev", group_index = 0 }
--
-- 	return res
-- end

return { -- Autocompletion
	-- "hrsh7th/nvim-cmp",
	-- event = "InsertEnter",
	-- dependencies = {
	-- 	-- Snippet Engine & its associated nvim-cmp source
	-- 	"L3MON4D3/LuaSnip",
	-- 	"saadparwaiz1/cmp_luasnip",
	-- 	"hrsh7th/cmp-nvim-lsp",
	-- 	"hrsh7th/cmp-path",
	-- },
	-- config = function()
	-- 	local cmp = require("cmp")
	-- 	local luasnip = require("luasnip")
	--
	-- 	cmp.setup({
	-- 		snippet = {
	-- 			expand = function(args)
	-- 				luasnip.lsp_expand(args.body)
	-- 			end,
	-- 		},
	-- 		completion = { completeopt = "menu,menuone,noinsert" },
	--
	-- 		-- For an understanding of why these mappings were
	-- 		-- chosen, you will need to read `:help ins-completion`
	-- 		--
	-- 		-- No, but seriously. Please read `:help ins-completion`, it is really good!
	-- 		mapping = cmp.mapping.preset.insert({
	-- 			-- Select the [n]ext item
	-- 			["<C-n>"] = cmp.mapping.select_next_item(),
	-- 			-- Select the [p]revious item
	-- 			["<C-p>"] = cmp.mapping.select_prev_item(),
	--
	-- 			-- Scroll the documentation window [b]ack / [f]orward
	-- 			["<C-b>"] = cmp.mapping.scroll_docs(-4),
	-- 			["<C-f>"] = cmp.mapping.scroll_docs(4),
	--
	-- 			["<C-Enter>"] = cmp.mapping.confirm({ select = true }),
	--
	-- 			-- Manually trigger a completion from nvim-cmp.
	-- 			--  Generally you don't need this, because nvim-cmp will display
	-- 			--  completions whenever it has completion options available.
	-- 			["<C-Space>"] = cmp.mapping.complete({}),
	--
	-- 			["<C-l>"] = cmp.mapping(function()
	-- 				if luasnip.expand_or_locally_jumpable() then
	-- 					luasnip.expand_or_jump()
	-- 				end
	-- 			end, { "i", "s" }),
	-- 			["<C-h>"] = cmp.mapping(function()
	-- 				if luasnip.locally_jumpable(-1) then
	-- 					luasnip.jump(-1)
	-- 				end
	-- 			end, { "i", "s" }),
	-- 		}),
	-- 		sources = sources_gen(),
	-- 	})
	-- end,
}
